# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: ibmcloudacademy/lightbluecompute-mysql
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: mysql-lightblue-service
  type: NodePort
  externalPort: 3306
  internalPort: 3306
  nodePort: 30006
