# Default values for customer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: ibmcloudacademy/lightbluecompute-customer
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: customer-lightblue-service
  type: NodePort
  externalPort: 8080
  internalPort: 8080
  nodePort: 30110
